module.exports = {
  apps: [
    {
      name: 'discord-always-online-idler',
      script: 'main.py',
      interpreter: './venv/bin/python3',
      cwd: __dirname,
      env: {
        TOKENS: 'token1, token2, token3, token4, token5',
        HUMAN_SCHEDULE_MODE: 'true',
        TIMEZONE: 'Europe/Amsterdam',
        SLEEP_TIME_START: '21',
        SLEEP_TIME_END: '2',
        WAKE_TIME_START: '6',
        WAKE_TIME_END: '10',
        GAME_ACCOUNTS: '',
        GAME_NAME: 'GAME NAME',
        GAME_IMAGE: 'https://cdn.discordapp.com/app-icons/',
        GAME_SESSIONS: '10-15,18-23',
        MIN_PLAY_HOURS: '2',
        MAX_PLAY_HOURS: '5',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      out_file: './pm2-out.log',
      error_file: './pm2-error.log',
      time: true,
    },
  ],
};
